apiVersion: template.alauda.io/v1
kind: Template
metadata:
  creationTimestamp: 2025-05-27T09:47:40Z
  generation: 6
  name: namespace-quota-limit
  namespace: cpaas-system
  resourceVersion: "26588497"
  uid: 185d1f8f-0fa4-4a4b-8bca-61d6ff5fe9b3
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        cpaas.io/cluster: ${CLUSTER}
        cpaas.io/project: ${PROJECT}
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/warn: restricted
        security.cpaas.io/enabled: "true"
      name: ${NAMESPACE}
    spec:
      finalizers:
        - kubernetes
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: default
      namespace: ${NAMESPACE}
    spec:
      hard:
        limits.cpu: "4"
        limits.memory: 8Gi
        pods: "10"
        requests.cpu: "2"
        requests.memory: 4Gi
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: default
      namespace: ${NAMESPACE}
    spec:
      limits:
        - default:
            cpu: 500m
            memory: 512Mi
          defaultRequest:
            cpu: 250m
            memory: 256Mi
          max:
            cpu: "1"
            memory: 1Gi
          min:
            cpu: 100m
            memory: 128Mi
          type: Container
parameters:
  - description: The name of the namespace
    displayName: namespaceName
    name: NAMESPACE
    required: true
  - description: The name of the project which the namespace belongs to
    displayName: projectName
    name: PROJECT
    required: true
  - description: The name of the cluster which the namespace belongs to
    displayName: clusterName
    name: CLUSTER
    required: true
