# Creating a Network Attachment Definition
# NetworkAttachmentDefinition-subnet.yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan			
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth1",		# Host interface that connects to the external network
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "macvlan.default"		# format <network attachment definition name>.<namespace>
      }
    }'
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: macvlan
spec:
  protocol: IPv4
  provider: macvlan.default
  cidrBlock: 172.17.10.0/24		# Egress gateway nodes cidr
  gateway: 172.17.0.1			# Egress gateway node's gateway
  excludeIps:
    - 172.17.10.251	# mainly exclude egress gateway node's gateway ip
# kubectl create -f NetworkAttachmentDefinition-subnet.yaml

# edit VPC
# kubectl  edit vpc ovn-cluster
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: ovn-cluster
spec:
  bfdPort:					# Add the follower.
    enabled: true
    ip: 10.255.255.255
    nodeSelector:
      matchLabels:
        egress: ""

# Creating a VPC Egress Gateway
# veg.yaml
apiVersion: kubeovn.io/v1
kind: VpcEgressGateway
metadata:
  name: egress-gateway
  namespace: default
spec:
  replicas: 3
  bfd:
    enabled: true
    minRX: 100
    minTX: 100
    multiplier: 5
  externalSubnet: macvlan
  externalIPs: 
  - <egress node ip1>
  - <egress node ip2>
  - <egress node ip3>
  nodeSelector:
    - matchExpressions:
        - key: egress
          operator: In
          values:
            - ""
  tolerations:
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoSchedule
  selectors:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ns-1 
  trafficPolicy: Cluster
  vpc: ovn-cluster
# kubectl create -f veg.yaml

# Add toleration to egress-gateway
# kubectl  edit deploy -n kube-system egress-gateway
# spec.template.spec.containers.tolerations
       tolerations:
       - effect: NoSchedule
         key: node-role.kubernetes.io/infra
         operator: Exists
