apiVersion: auth.alauda.io/v1beta1
kind: RoleTemplate
metadata:
  name: monitor-customrules
  annotations:
    cpaas.io/display-name: Custom Rules Role for monitor
    cpaas.io/description: Custom Rules Role for monitor
  labels:
    auth.cpaas.io/roletemplate.level: cluster
spec:
  customRules:
    - apiGroup: monitoring.alauda.io
      bindCluster: global
      bindNamespacePart: common
      bindScope: namespace
      resources:
        - metrics
    - apiGroup: monitoring.alauda.io
      bindCluster: global
      bindNamespacePart: project_ns
      bindScope: namespace
      resources:
        - metrics
